const PathConstants = {
    HOME: '',
    LOGIN: '/login',
    ESEBP2: '/form-1',
    COLABORADOR: '/colaborador',
    CALIDAD: '/calidad',
    CLIENTES: '/clientes',
    CLIENTEACTUALIZAR: '/clientes/:ID',
    CLIENTENUEVO: '/clientes/nuevo',
    COLEGIOSCOMUNES: '/colegios/comunes',
    ENCUESTAS: '/encuestas',
    ENCUESTASID: '/encuestas/:ID',
    TIPOSCLIENTES: '/tipos-clientes',
    FAMILIAS: '/familias',
    FAMILIASALTA: '/familias/:IDFAMILIA',
    FAMILIASFILES:'/familias/archivos',
    PERFILES: '/perfiles',
    USUARIOS: '/usuarios',
    CICLOSESCOLARES: '/ciclos-escolares',
    PROYECTOS: '/proyectos',
    PROYECTO: '/proyectos/:ID',
    SERVICIOESTUDIO: '/servicio-estudio',
    ESTUDIOSOCIOECONOMICO: '/estudio-socioeconomico',
    ESTUDIOSOCIOECONOMICONUEVO: '/estudio-socioeconomico/nuevo/:idProyecto/:idCliente/:idOrdenServicio',
    ESTUDIOLABORAL: '/estudio-laboral',
    ESTUDIOLABORALNUEVO: '/estudio-laboral/nuevo/:idCliente/:idOrdenServicio?',
}

export default PathConstants