const PathConstants = {
    HOME: '',
    LOGIN: '/login',
    ESEBP2: '/form-1',
    DATOSFAMILIA: '/datos-familia',
    COLABORADOR: '/colaborador',
    CALIDAD: '/calidad',
    CLIENTES: '/clientes',
    CLIENTEACTUALIZAR: '/clientes/:ID',
    CLIENTENUEVO: '/clientes/nuevo',
    COLEGIOSCOMUNES: '/colegios/comunes',
    ENCUESTAS: '/encuestas',
    ENCUESTASID: '/encuestas/:ID',
    TIPOSCLIENTES: '/tipos-clientes',
    FAMILIAS: '/familias',
    FAMILIASALTA: '/familias/:IDFAMILIA',
    FAMILIASFILES:'/familias/archivos',
    PERFILES: '/perfiles',
    USUARIOS: '/usuarios',
    USUARIOCREAR: '/usuarios/crear',
    USUARIOACTUALIZAR: '/usuarios/:id/actualizar',
    USUARIOVER: '/usuarios/:id/ver',
    CICLOSESCOLARES: '/ciclos-escolares',
    PROYECTOS: '/proyectos',
    PROYECTO: '/proyectos/:ID',
    SERVICIOESTUDIO: '/servicio-estudio',
    ESTUDIOSOCIOECONOMICO: '/estudio-socioeconomico',
    ESTUDIOSOCIOECONOMICOID: '/estudio-socioeconomico/:idEstudio',
    ESTUDIOSOCIOECONOMICOIDFAMILIA:'estudio-socioeconomico/editar-familia/:idEstudio',
    ESTUDIOSOCIOECONOMICONUEVO: '/estudio-socioeconomico/nuevo/:idProyecto/:idCliente/:idOrdenServicio',
    ESTUDIOLABORAL: '/estudio-laboral',
    ESTUDIOLABORALNUEVO: '/estudio-laboral/nuevo/:idCliente/:idOrdenServicio?',
    ESTUDIOS: '/estudios',
    ESTUDIOID: '/estudio/:idEstudio',
    ESTUDIOSID: '/estudios/:idEstudio',
    ESTUDIO_SOCIOECONOMICO_ID: '/estudio-socioeconomico/:idEstudio',
    ENCUESTAPROYECTOID: '/encuesta/proyecto/:idProyecto',
    
}

export default PathConstants